### ISSUE TITLE
Support filtering group query by memberUid

### ISSUE THREAD

**Issue by khimaros** [clems4ever/authelia#102]
This requires specifying the username instead of DN, which would require changes to the format string.

**Comment by clems4ever** [comment]
Hello @sllawap , thank you for the proposal but I'm not sure I understood the issue you're trying to solve. Can you please elaborate providing a concrete use case?

**Comment by sllawap** [comment]
Assume the following:

```
dn: cn=people,ou=groups,dc=zone
cn: people
gidnumber: 1000
memberuid: user1
memberuid: user2
objectclass: top
objectclass: posixGroup
```

I'd like to be able to match in the config:

```
ldap:
  base_dn: dc=zone
  additional_groups_dn: ou=groups
  group_name_attribute: cn
  groups_filter: memberuid={username}
```

Where `{username}` would be replaced by the uid of the user being signed in rather than the full DN.
