### ISSUE TITLE
Feature request: Restrict access to URL by group

### ISSUE THREAD

**Issue by jkaberg** [clems4ever/authelia#20]
I'd love to see an option in the config where one could specify which LDAP group has access to what urls, and an default policy 😃 

For example (yaml):

```
access:
  default: [] (default == everyone/anyone)
  users:
    - blog.domain.tld
    - chat.domain.tld
  admin:
    - *.domain.tld (everything)
  superuser:
    - phpmyadmin.domain.tld
    - *.mail.domain.tld (access to mail.domain.tld and all subdomains of mail)
```
So if my user is in group admin, superuser and users group I get access to all these subdomains or if my user is in group users and superuser I only get access to these urls.
