### ISSUE TITLE
Make Authelia available on Kubernetes using ingress-nginx

### ISSUE THREAD

**Issue by clems4ever** [clems4ever/authelia#206]
It would be great to have Authelia in a Kube cluster in only few commands (only one?).
Plus, in combination with kube-lego, certificates renewal can be handled automatically by the cluster.

https://github.com/kubernetes/ingress-nginx

**Comment by clems4ever** [comment]
FYI, I've made it working in my cluster with kube-lego for certificate renewal. I will publish configurations to show how to set it up. Hopefully I will package it with Helmet at some point.

**Comment by clems4ever** [comment]
I made it work with branch called `kube`. There is a README in example/kubernetes directory. Please give your feedback if you follow the steps, it would be greatly appreciated.

**Comment by damomurf** [comment]
So I’ve got Authelia working mostly fine under Nginx-ingress in Kubernetes without this.

The only thing not working are redirects after login. What did you have to change to get that to work?

I’d rather not replace the whole Nginx-ingress template, but use annotations for config if I can.

**Comment by clems4ever** [comment]
Hello @damomurf , this statement might be missing in the nginx template:
```
auth_request_set    $redirect $upstream_http_redirect;
```

I'm really interested in your configuration though. Which version of nginx-ingress do you use and what is an example of ingress configuration working with Authelia? Can you please share it?

**Comment by clems4ever** [comment]
If you want to see all the changes I've done for version 0.9.0-beta.19 of the nginx controller to make it work, you can `diff -u` the two files in `example/kube/ingress-controller/configs`. It gives this:

```
--- nginx.tmpl	2017-11-29 02:03:17.000000000 +0100
+++ configs/nginx.tmpl	2018-03-04 12:32:14.106051659 +0100
@@ -647,8 +647,10 @@
             proxy_set_header            X-Scheme                $pass_access_scheme;
             {{ end }}
 
-            proxy_set_header            Host                    {{ $location.ExternalAuth.Host }};
-            proxy_set_header            X-Original-URL          $scheme://$http_host$request_uri;
+            proxy_set_header            Host                    $http_host;                                  
+            proxy_set_header            X-Original-URI          $request_uri;                      
+            proxy_set_header            X-Real-IP               $remote_addr;                           
+            proxy_set_header            X-Forwarded-Proto       $scheme;
             proxy_set_header            X-Original-Method       $request_method;
             proxy_set_header            X-Auth-Request-Redirect $request_uri;
             proxy_set_header            X-Sent-From             "nginx-ingress-controller";
@@ -705,6 +707,12 @@
             # this location requires authentication
             auth_request        {{ $authPath }};
             auth_request_set    $auth_cookie $upstream_http_set_cookie;
+            auth_request_set    $redirect $upstream_http_redirect;                 
+            auth_request_set    $user $upstream_http_remote_user;                  
+            proxy_set_header    X-Forwarded-User $user;                            
+            auth_request_set    $groups $upstream_http_remote_groups;              
+            proxy_set_header    Remote-Groups $groups;
+            
             add_header          Set-Cookie $auth_cookie;
             {{- range $idx, $line := buildAuthResponseHeaders $location }}
             {{ $line }}

```

**Comment by damomurf** [comment]
@clems4ever The ingress configuration I use is as follows: 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: authelia-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: login.domain
    http:
      paths:
      - backend:
          serviceName: authelia-service
          servicePort: 80
        path: /
  tls:
  - hosts:
    - login.domain
    secretName: authelia-tls
```
Everything works fine, except after logging in with Authelia, no redirect is sent to the originally requested URL. If there's already a valid session, everything works as expected.

I'm using the following docker image:
`quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0-beta.19`

I might try with server-snippet annotations in the ingress and see if I can get them to add the auth_request_set variables?

**Comment by damomurf** [comment]
Oh, and an Ingress requiring Authelia for auth looks like: 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-signin: https://login.domain
    nginx.ingress.kubernetes.io/auth-url: https://login.domain/api/verify
spec: 
  tls:
  - secretName: prometheus-tls
    hosts:
    - prometheus.domain
  - secretName: alertmanager-tls
    hosts:
    - alertmanager.domain
  rules:
  - host: prometheus.domain
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: 9090
  - host: alertmanager.domain
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: 9093
```
