### ISSUE TITLE
Help with single-factor

### ISSUE THREAD

**Issue by davama** [clems4ever/authelia#208]
Im trying to use single factor but on certain domains but cant seem to make it work...

authelia server is `login.nwk.jwm2.net`
graylog server authenticating via authelia `graylog-lab.nwk.jwm2.net`

authelia config (what i think is relevant):
```
authentication_methods:
  default_method: two_factor
  per_subdomain_methods:
    single_factor.graylog-lab.nwk.jwm2.net: single_factor
access_control:
  default_policy: deny
  any:
    - domain: login.nwk.jwm2.net
      policy: allow  
  groups:
    gateone:
      - domain: 'gateone.nwk.jwm2.net'
        policy: allow
        resources:
          - '^/gateone.*$'
    syslog:
      - domain: 'graylog-lab.nwk.jwm2.net'
        policy: allow
        resources:
          - '^/graylog.*$' 
session:
  secret: unsecure_session_secret
  expiration: 86400000 # 24 hours
  inactivity: 86400000 # 24 hours
  domain: nwk.jwm2.net
...
...
```

If i set `default_methos` and `single_factor` to `single_factor` then single factor auth works.

if i leave as above the 2fa is the only method allowed on all domains. 
Any input is appreciated

thanks,
dave
