### ISSUE TITLE
Authelia loses track of authenticated users

### ISSUE THREAD

**Issue by jkaberg** [clems4ever/authelia#24]
Whenever I restart the authelia container it forgets authenticated users, which results in the need to authenticate again.

I'm mounting the container as such:

```
  auth:
    image: clems4ever/authelia
    restart: always
    depends_on:
      - freeipa
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/storage/authelia/config.yml:/etc/auth-server/config.yml:ro
      - /path/to/storage/authelia/notifications:/var/lib/auth-server/notifications
      - /path/to/storage/authelia/store:/var/lib/auth-server/store
    networks:
      - backend
```
Browsing the store folder looking into the files tells me things get stored correctly. So I'm assuming this might be an oversight in the code? Or is this by design?
