### ISSUE TITLE
How to use with docker-compose?

### ISSUE THREAD

**Issue by mnlbox** [clems4ever/authelia#248]
@clems4ever I want to use this awesome tools with docker-compose and mix this with parse platform.
Now I'm using https://github.com/bitnami/bitnami-docker-parse-dashboard  for up and running mongodb + parse-platform + parse-dashboard
I also search a lot for a 2FA solution for parse [here](https://github.com/parse-community/parse-server/issues/4024) and [here](https://github.com/parse-community/parse-dashboard/issues/856).

Can you guide me how to add Authelia and openLDAP as a new part to below docker-compose:
```
version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - '8080:27017'
    volumes:
      - './mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:latest'
    ports:
      - '1337:1337'
    volumes:
      - './parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:4040'
    volumes:
      - './parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```
