### ISSUE TITLE
Unable to detech hash salt and rounds in minimal docker install

### ISSUE THREAD

**Issue by Svarto** [clems4ever/authelia#307]
Hi,

I tried to set up a test environment with Authelia, to try it out before committing it to my homelab. I have set it up and can correctly navigate to the webpage, and get the login page, on http://home-ip:8080.

However, when I try to login, using a different hashed password than "mypassword", I get an authentication failure and the following error in my logs:

`error: date='Sun Dec 16 2018 20:47:29 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='xxx' sessionId='xxx' ip='desktop-ip' message='Reply with error 200: Unable to detect the hash salt and rounds. Make sure the password is hashed with SSHA512.'`

So it can find the file, but somehow not detect if the hash is correct. I have the following in my users_database.yml:

```
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  test_user:
    password: "{CRYPT}$6$rounds=500000$W/8aYO.7Nb2SqIgd$TOXDeaMicSWZ.9BU/VafTxjVICwFl77zvR2NT0AV/tJ7pscfEgr7omY/CRN.Gdqbr7XKb6DsKnHbWNrRSFgtm0"
    email: myemail@mail.com
    groups:
      - admins
      - dev
```

Hope you can help me?

TLDR: Error is thrown when using a different password to the default mypassword.
