### ISSUE TITLE
[Question]: Configuring multiple backend servers

### ISSUE THREAD

**Issue by davama** [clems4ever/authelia#392]
Hello,

Was wondering how to configure multiple ldap/mongo/redis servers for high availability. Also, how include the replica set of mongo?
Do each of these module (ldap,redis,mongo) keep track of who is master or alive/dead?

```
ldap: 
   url: ldap://srv1,srv2,srv3 

redis:
   host: srv1,srv2,srv3

mongo:
  url: mongo://srv1,srv2,srv3/replicaset0
```

can one use dns SRV records for ldap and mongo?

Hope this makes sense.

Thank you,
Dave
