### ISSUE TITLE
Request: Support ACL with subfolder

### ISSUE THREAD

**Issue by ColdIce1** [clems4ever/authelia#43]
Would like support for "subfolder" ACL.
Nginx conf example:
```
# Proxy pass for internal blog with Authelia authentication
 location /blog {
        auth_request /auth_verify;

        auth_request_set $user $upstream_http_x_remote_user;
        proxy_set_header X-Forwarded-User $user;
        auth_request_set $groups $upstream_http_remote_groups;
        proxy_set_header Remote-Groups $groups;
        auth_request_set $expiry $upstream_http_remote_expiry;
        proxy_set_header Remote-Expiry $expiry;

        proxy_pass http://192.168.10.13:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

ACL config in Authelia:
```
access_control:
  groups:
    admins:
      - 'web.mydomain.com/blog
      - 'web.mydomain.com/admin-site'
    blog-view:
      - 'web.mydomain.com/blog'
```

**Comment by clems4ever** [comment]
Hello @ColdIce1, it would be a great idea actually. Do not hesitate to contribute otherwise I'll handle it.

**Comment by clems4ever** [comment]
Hello @ColdIce1, actually the feature is a bit more complicated that I expected in terms of definition. Here is the kind of config I ended up with so far:

```
access_control:
  default_policy: deny

  # The rules that apply to anyone.
  # The value is a list of rules.
  all:
    - domain: public.test.local
      policy: allow
  
  # Group based rules. The key is a group name and the value
  # is a list of rules.
  groups:
    admin:
      - domain: '*.test.local'
        policy: allow
      - domain: '*.test.local'
        resources: 
          - '^/admins'
        policy: deny
      - domain: 'secret.test.local'
        resources: 
          - '^/admins/'
        policy: allow
    dev:
      - domain: secret.test.local
        policy: allow
      - domain: secret2.test.local
        policy: allow
  
  # Group based rules. The key is a user name and the value
  # is a list of rules.
  users: 
    harry:
      - domain: secret1.test.local
        policy: allow
    bob:
      - domain: '*.mail.test.local'
        policy: allow
      - domain: 'secret.test.local'
        policy: allow
        resources: 
          - '^/users/bob/'
```
'Resources' is a list of regexp in order to have the maximum flexibility.
What do you think?
