### ISSUE TITLE
Feature: Set Headers in Access Control Rules

### ISSUE THREAD

**Issue by james-d-elliott** [clems4ever/authelia#441]
I'm not sure how portable this would be, but I believe traefik 1.7 k8s ingress supports relaying a header set by the authentication service to the final request to the service (https://docs.traefik.io/v1.7/configuration/backends/kubernetes/#authentication). It would be useful to be able to specify per rule in access control, a list of headers to apply to the response.

Ideally it would also support mapping to LDAP attributes. 

For example:

```
access_control:
  default_policy: deny

  rules:
    # Rules applied to everyone
    - domain: public.example.com
      policy: bypass
    - domain: secure.example.com #example of staticaly setting the value, for a single user
      subject: 'user:admin'
      policy: two_factor
      headers:
      - name: X-Auth-Token
        value: dG9rZW4gdGhhdCBkZWNsYXJlcyBhdXRoZWxpYSBpcyBhd2Vzb21l
    - domain: secure.example.com #example of pulling the value from the ldapUser and setting it dynamically, for a single user
      policy: two_factor
      headers
      - name: X-Auth-Token
        ldapAttribute: tokenAttribute
```
