### ISSUE TITLE
Active Directory backend broken on v4

### ISSUE THREAD

**Issue by Hakujou** [clems4ever/authelia#451]
Hello,

The following backend used to work on v3, but does not on v4:
```
  ldap:
    # The url of the ldap server
    url: ldap://myadserver.internal.mydomain.com

    # The base dn for every entries
    base_dn: DC=internal,DC=mydomain,DC=com

    # An additional dn to define the scope to all users
    additional_users_dn: 'OU=Domain Users'

    # The users filter used to find the user DN
    # {0} is a matcher replaced by username.
    # 'cn={0}' by default.
    users_filter: sAMAccountName={0}

    # An additional dn to define the scope of groups
    additional_groups_dn: ou=Groupes

    # The groups filter used for retrieving groups of a given user.
    # {0} is a matcher replaced by username.
    # {dn} is a matcher replaced by user DN.
    # {uid} is a matcher replaced by user uid.
    # 'member={dn}' by default.
    groups_filter: (&(member={dn})(objectclass=group))

    # The attribute holding the name of the group
    group_name_attribute: cn

    # The attribute holding the mail address of the user
    mail_attribute: mail

    # The username and password of the admin user.
    user: CN=bob,CN=Users,DC=internal,DC=mydomain,DC=com
    password: SuperSecurePasswordHere
```

I now get this error when trying to login:
`"Error while checking password for user myuser: Cannot find user DN of user myuser. Cause: LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('"`

Am I doing something wrong ?
Thanks :)
