### ISSUE TITLE
Authelia V4 not working with traefik as it did before

### ISSUE THREAD

**Issue by zackpollard** [clems4ever/authelia#472]
I updated to authelia v4 today and everything seemed to work after I renamed my config from config.yml to configuration.yml. However, upon trying to login after browsing to one of my sites, I didn't get re-directed back to the site I came from. This was working before and seems to have been broken in v4. Was there any support removed that used to exist before? I'm happy to run through my config etc to help debug what has broken in the update, would just like to get this issue resolved if possible so i'm not stuck on v3.

**Comment by clems4ever** [comment]
Hello @zackpollard , it's supposed to work and it does in the e2e tests.
Please share the URL you have in 1FA.

**Comment by zackpollard** [comment]
At the login screen I simply have this URL https://{DOMAIN}/

**Comment by zackpollard** [comment]
My auth forward address in traefik is `http://authelia:8080/api/verify?rd=https://{AUTH_DOMAIN}/%23/"`

**Comment by clems4ever** [comment]
Which docker tag do you use?

**Comment by clems4ever** [comment]
I meant the URL you see in your browser when you authenticated with username and password. Can you also provide me with the docker tag your deployed.

**Comment by zackpollard** [comment]
After authentication I get taken to the 2FA page as it doesn't know where to route me, so it takes me to the 2FA page by default. I am using the master tag

**Comment by clems4ever** [comment]
First, if you use the master tag you can remove /%23/ from the redirection url to the auth domain, it's not needed anymore. Then, routing you to 2FA is expected unless you use one_factor policy for your domain. What are you expecting?

**Comment by clems4ever** [comment]
I've just read everything again to be sure I get your point and I think the issue starts when you get the following url at 1FA stage: https://{AUTH_DOMAIN}/.

The URL should contain ?rd=https://{YOUR_SITE} for you to be redirected upon successful authentication.

**Comment by clems4ever** [comment]
It should be  https://{AUTH_DOMAIN}/?rd=https://{YOUR_SITE} in your browser.

**Comment by zackpollard** [comment]
Agreed, however this has broken now that I am using version 4

**Comment by zackpollard** [comment]
Without any config changes, this works on version 3, I believe it reads a header or cookie set by traefik to figure out where to redirect, as I remembered I was able to remove that from the redirect URL in the traefik config on a per-site basis. Also yes, the domain is set to use on_factor policy mode, authelia is treating it as if I have navigated directly to the AUTH_DOMAIN and so takes me to 2FA page.

**Comment by clems4ever** [comment]
Well if you hadn't `?rd=https://{YOUR_SITE}` in v3 and still got redirected, it was a bug... Traefik uses X-Fowarded-* headers to get redirected to the correct URL. I'll need your traefik config to be able to help you further.

**Comment by clems4ever** [comment]
and perhaps Authelia logs would help too.

**Comment by zackpollard** [comment]
Authelia logs
```time="2019-12-05T17:06:01Z" level=info msg="Logging severity set to debug"


Selected public_html directory is  ./public_html


time="2019-12-05T17:06:01Z" level=info msg="Authelia is listening on :8080"


time="2019-12-05T17:06:09Z" level=debug msg="Credentials validation of user zack is ok" method=POST path=/api/firstfactor remote_ip=192.168.16.10


time="2019-12-05T17:06:09Z" level=debug msg="Mark authentication attempt made by user zack" method=POST path=/api/firstfactor remote_ip=192.168.16.10


time="2019-12-05T17:06:09Z" level=debug msg="Available methods are [totp u2f]" method=GET path=/api/secondfactor/available remote_ip=192.168.16.10


time="2019-12-05T17:06:09Z" level=debug msg="Loaded prefered 2FA method of user zack is " method=GET path=/api/secondfactor/preferences remote_ip=192.168.16.10```

**Comment by zackpollard** [comment]
Traefik Config
```
defaultEntryPoints = [ "https", "http" ]

insecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
    [entryPoints.https.auth]
      [entryPoints.https.auth.forward]
        address = "http://authelia:8080/api/verify?rd=https://{AUTH_DOMAIN}/%23/"

[retry]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "{DOCKER_DOMAIN}"
  watch = true
  exposedByDefault = false
  network = "proxy"

[acme]
  email = "zackpollard@ymail.com"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"
```

**Comment by zackpollard** [comment]
I believe in V3 the ?rd=domain query parameter was set, but it was set from the X-Forwarded-* headers as you said. It was a while back that I did the config for this so I don't remember the specifics, I just remember watching the progress towards the header solution in authelia as before that you had to set it up on a per-domain basis in the traefik config

**Comment by clems4ever** [comment]
Traefik config looks good. Can you set the level of logs to debug and retry? I'll also need the Traefik labels of the authelia container and the ones from the service you want to be redirected to.

**Comment by clems4ever** [comment]
Can you please set the level of logs to trace and give me the labels of Authelia container and the ones from the service you want to be redirected to.

**Comment by clems4ever** [comment]
Also, it seems the logs you extracted are from an authentication attempt where rd= is not provided like if you directly visited the auth portal.
Can you send me the logs of the following scenario: visit the service as unauthenticated user, get redirected and then proceed with 1FA authentication.

**Comment by zackpollard** [comment]
I will get that stuff across to you shortly. The logs I sent are for the scenario you described. Go to service unauthenticated, get redirected, login with 1FA

**Comment by zackpollard** [comment]
```
  authelia:
    image: clems4ever/authelia:master
    restart: always
    volumes:
      - /mnt/user/appdata/traefik/authelia/configuration.yml:/etc/authelia/configuration.yml:ro
      - /mnt/user/appdata/traefik/authelia/users_database.yml:/etc/authelia/users_database.yml:rw
      - /tmp/authelia:/tmp/authelia
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=1
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:{AUTH_DOMAIN}"
      - "traefik.port=8080"
```

**Comment by zackpollard** [comment]
Example service docker compose
```
  whoami:
    image: containous/whoami  # A container that exposes an API to show its IP address
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.frontend.rule=Host:{SERVICE_DOMAIN} "
      - "traefik.enable=true"
```
