### ISSUE TITLE
Protect SSH accesses with Authelia

### ISSUE THREAD

**Issue by clems4ever** [clems4ever/authelia#497]

**Comment by kusold** [comment]
Since Authelia uses LDAP as the backing data store, why wouldn't someone just use [libpam-ldapd](https://wiki.debian.org/LDAP/PAM)?

**Comment by clems4ever** [comment]
After having run a quick search, I don't think libpam-ldapd supports 2FA, does it? That would be the point, i.e., add an extra layer of security to SSH by using a single integrated authentication solution.

**Comment by nightah** [comment]
I actually currently utilise Duo for this function with https://duo.com/docs/duounix.
Which provides only the second factor, if we did something similar with Authelia it would basically be like providing both the above and https://github.com/google/google-authenticator-libpam.

**Comment by clems4ever** [comment]
Great feedback @nightah , thanks.

**Comment by davama** [comment]
We also use https://github.com/google/google-authenticator-libpam for SSH 2FA auth, but that is of course a different TOTP secret. 

I would assume that a similar approach to what they do would work 
`SSH PAM module > using secret stored in DB`

**Comment by davama** [comment]
Sorry just to add... instead of reinvent the wheel, (that google project already does a good job at it) why not simple `script` that executes when the authelia creates/updates the TOTP secret for a user? 

Of course that would mean that for 2FA SSH, there would be a dependency on another project, but I dont see that project being abandoned any time soon... 

my 2 cents

**Comment by clems4ever** [comment]
Thank you @davama for your report. I understand your concerns and I'm on par with the "don't reinvent the wheel" way of thinking. The point behind this issue is to support more than just TOTP as 2nd FA. Implementing the feature directly in Authelia will let admins choose any method supported by Authelia like security keys, push notifications and soon fingerprint or face recognition, smart cards or even delegated authentication with openid connect or whatever else... As a reminder, the objective behind Authelia is to avoid having multiple solutions to solve a unique and common problem because in most cases it's just harder to manage.
Note that I will for sure try to use as much already existing and supported opensource modules or library as I can for that. I haven't really taken the time to study this yet since it's low priority in my todo list but I'll definitely have a look at the mentioned solutions when time comes.

**Comment by nightah** [comment]
@davama much aligned with what @clems4ever has suggested, my point above was that we would almost be incorporating the above pam modules into an authelia distributed pam module.
We would need our own flavour over the top to ensure that the respective authentication mechanisms are aligned with what Authelia supports for the respective users but ideally we should be merging the upstream code in as modules.

**Comment by silopolis** [comment]
Hi guys, just starting to study how I could implement SSO and MFA into my study reference architecture and Authelia surely leads the race!
That said, SSH is the very second service I'd like to integrate with... Any news on this front?

Thanks for sharing your hard work with the world
Take care
J

**Comment by ikiris** [comment]
I would suggest most of ya'll to investigate SSH cert based auth. You can pretty easily gate 20 hour certs behind authelia sso, store the keys on hardware tokens, and as a bonus, it will still work if your auth infrastructure is offline. It's also a lot safer in general.

**Comment by DunklerPhoenix** [comment]
https://www.janua.fr/keycloak-ssh-connection-with-oauth2/

Here is an example with oauth2 with keycloak. It could theoretical work with authelia, but I didn't test it yet

**Comment by peter-** [comment]
Probably a bit old-school and not really using Authelia other than as a self-service UI for registering "keys" (which it does just great for TOTP shared secrets, FIDO U2F and FIDO2 security keys) but I'll note it anyway:

How about simply offering a text input field for people to paste their SSH public keys into (same as Github, Gitlab, Gitea, etc. are doing)? Systems intending to allow SSH logins using those keys can look up the key(s) from Authelia via API or cli (sub-)commands providing the userid as parameter -- just call the API or cli command from e.g. a 1-line script referenced in such a system's OpenSSHd `AuthorizedKeysCommand` (cf. [man page](https://man.openbsd.org/sshd_config#AuthorizedKeysCommand)).

**Comment by electrofloat** [comment]
This should already work with Authelia's device code flow.

Configure Authelia with something like this:
```
identity_providers:
  oidc:
    clients:
      - client_id: device-code-flow-client
        client_name: Device Flow Client
        client_secret: (the digest of 'secret')
        grant_types:
          - urn:ietf:params:oauth:grant-type:device_code
```

Then use https://github.com/ondrejvelisek/pam_oauth2_device with a config something like this:

```
oauth:
    client:
        id: 'device-code-flow-client'
        secret: 'secret'
    scope: [openid, profile, email]
    device_endpoint: https://auth.example.org/api/oidc/device-authorization
    token_endpoint: https://auth.exmaple.org/api/oidc/token
    userinfo_endpoint: https://auth.example.org/api/oidc/userinfo

.
.
.

```

I haven't tested the above as is, but have tested the python code itself, without the actual PAM usage and it worked for me.
