### ISSUE TITLE
TCP._handle.close [as _onclose] (net.js:511:12)

### ISSUE THREAD

**Issue by jkaberg** [clems4ever/authelia#77]
Seeing a lot of these recently, which makes POST/XHR requests fail.

Will debug further this weekend, just wondering if you've seen this before @clems4ever?

```
Error
    at IncomingMessage.onAborted (/usr/src/node_modules/raw-body/index.js:269:10)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at abortIncoming (_http_server.js:381:9)
    at socketOnClose (_http_server.js:375:3)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:511:12)
Error
    at IncomingMessage.onAborted (/usr/src/node_modules/raw-body/index.js:269:10)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at abortIncoming (_http_server.js:381:9)
    at socketOnClose (_http_server.js:375:3)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:511:12)
Error
    at IncomingMessage.onAborted (/usr/src/node_modules/raw-body/index.js:269:10)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at abortIncoming (_http_server.js:381:9)
    at socketOnClose (_http_server.js:375:3)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:511:12)
Error
    at IncomingMessage.onAborted (/usr/src/node_modules/raw-body/index.js:269:10)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at abortIncoming (_http_server.js:381:9)
    at socketOnClose (_http_server.js:375:3)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:511:12)
Error
    at IncomingMessage.onAborted (/usr/src/node_modules/raw-body/index.js:269:10)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at abortIncoming (_http_server.js:381:9)
    at socketOnClose (_http_server.js:375:3)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:511:12)
Error
    at IncomingMessage.onAborted (/usr/src/node_modules/raw-body/index.js:269:10)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at abortIncoming (_http_server.js:381:9)
    at socketOnClose (_http_server.js:375:3)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:511:12)
```

**Comment by clems4ever** [comment]
Hello @jkaberg,
wow, I have not seen this before. Are you still deploying from the example?
Are all your external services (ldap, redis, mongo) up and running and accessible from Authelia?
Can you provide me with your commit id and config file if customized?

**Comment by jkaberg** [comment]
@clems4ever Did some debugging now, so Authelia is able to connect to both Redis and MongoDB. I've also tried commenting them out of the config to see what happens and the error persist so I don't think it's related to Redis or MongoDB. Authelia is able to auth against LDAP just fine, actually the entire auth process with LDAP login and TOTP/2FA works as expected. 

I'm using the latest Docker image.

```
port: 80
logs_level: info
ldap:
  url: ldaps://xxxxx
  base_dn: dc=xxxxx,dc=xxxxx
  additional_users_dn: cn=users,cn=accounts
  users_filter: uid={0}
  user_name_attribute: uid
  additional_groups_dn: cn=groups,cn=accounts
  group_name_attribute: cn
  groups_filter: (&(member={0})(objectclass=groupOfNames))
  mail_attribute: mail
  user: uid=authelia,cn=sysaccounts,cn=etc,dc=xxxxx,dc=xxxxx
  password: xxxxx

access_control:
  default:
    - xxxxx
  groups:
    admins:
      - '*.xxxxx'

session:
  secret: xxxxx
  expiration: xxxxx
  domain: xxxxx
  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
        #  local: /var/lib/authelia/store
  mongo:
    url: mongodb://mongodb:27017/auth

notifier:
  gmail:
    username: xxxxx
    password: xxxxx
```

The issue arises (it seem's) when NGINX is hit with an POST/XHR request where NGINX asks (on the /verify endpoint) Authelia if auth is ok, where Authelia outputs the error message in 1st post
