### ISSUE TITLE
Messages about mssing infrastructure

### ISSUE THREAD

**Issue by Rast1234** [clems4ever/authelia#78]
Hello. Just installed authelia with docker-compose and got error like `TypeError: Cannot read property ‘auth’ of undefined \\ at Object.get (/usr/src/lib/AuthenticationSession.js:19:21)`. Spent some time understanding what's wrong until i realised that redis instance was in different network. Since authelia depends only on mongo, redis and openldap, maybe it's posible to add checks and human readable massages in case of similar exceptions to make it easier to set up? Like "mongo/redis/openldap server at <server_address> is unavailable, check your environment"

**Comment by clems4ever** [comment]
Hello @Rast1234 , thank you for reporting. 
Have you directly used the docker-compose command to deploy or the provided script (given in the README)?

**Comment by Rast1234** [comment]
I made custom docker-compose file myself. I checked that mongo/redis/ldap containers are available by logging in authelia container and pinging relevant hostnames.
Here is my `docker-compose.yml` if you are interested:
```
version: '2'
services:
  authelia:
    image: clems4ever/authelia
    container_name: authelia
    volumes:
      - /mnt/stuff/docker/authelia/config:/etc/authelia
      - /mnt/stuff/docker/authelia/data:/var/lib/authelia
    ports:
      - "42011:8080"
    links:
      - mongo:mongodb
      - openldap
    external_links:
      - redis
    network_mode: bridge

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - /mnt/stuff/docker/mongo:/data/db
    ports:
      - "27017:27017"
    network_mode: bridge

  openldap:
    image: dinkel/openldap
    container_name: openldap
    volumes:
      - /mnt/stuff/docker/openldap/conig:/etc/ldap
      - /mnt/stuff/docker/openldap/data:/var/lib/ldap
    environment:
      - SLAPD_PASSWORD=headshot
      - SLAPD_DOMAIN=rast.rocks
    network_mode: bridge

  phpldapadmin:
    image: dinkel/phpldapadmin
    container_name: phpldapadmin
    links:
      - openldap
    network_mode: bridge
    ports:
      - "8081:80"

```
